name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build && swift test
      
  deploy-dev:
    runs-on: macos-latest
    environment:
      name: dev
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build && swift test && echo Deploy Dev!
