name: Swift

on:
  pull_request:
    branches: [ realise ]
  


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build && swift test
