name: Swift

on:
  push:
    branches: [ realise ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo TO MAIN

